name: ci

on:
  push:
    branches:
      - main

env:
  USERNAME: ${{secrets.DOCKER_USERNAME}}
  PASSWORD: ${{secrets.DOCKERHUB_TOKEN}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      - 
        name: downcase REPO
        run: |
          echo "REPO=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: '${{github.event.repository.name}}'
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{env.USERNAME}}
          password: ${{env.PASSWORD}}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and test
        uses: docker/build-push-action@v5
        with:
          context: .
          target: build
          load: true
      -
        name: Build and push without action@v5
        run: | 
          docker tag ${{env.REPO}}-image ${{env.USERNAME}}/${{env.REPO}}
          docker push ${{env.USERNAME}}/${{env.REPO}}:latest
        # name: Build and push
        # uses: docker/build-push-action@v5
        # with:
        #   context: .
        #   push: true
        #   target: final
        #   tags: ${{env.USERNAME}}/${{env.REPO}}:latest
