name: ci

on:
  push:
    branches:
      - main

env:
  USERNAME: ${{secrets.DOCKER_USERNAME}}
  PASSWORD: ${{secrets.DOCKERHUB_TOKEN}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      - name: downcase REPO
        run: |
          echo REPO=${github.event.repository.name@L} >> ${GITHUB_ENV}
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{env.USERNAME}}
          password: ${{env.PASSWORD}}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and test
        uses: docker/build-push-action@v5
        with:
          context: .
          target: build
          load: true
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          target: final
          tags: ${{ secrets.DOCKER_USERNAME }}/${{env.REPO}}:latest
